export const environment = {
  lansUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/lans',
  newLansUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/lans/available',
  boardsUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards',
  newBoardsUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards/available',
  newBoardsBookingUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/boardbookingclose',
  openBoardsUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/openbookings',
  lanBookingUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/lanbooking',
  bookingsByDateUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/bookingsbydate',
  bookingsById: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/bookingbyid',
  boardsBySeats: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards/byseats',
  loginUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/auth/login',
  logoutUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/auth/logout',
  bookingsUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings',
  deleteBookingUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings',
  deleteStationUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api',
  updateBoardUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards',
  postStationUrl: 'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/save',
  editBookingUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings',
  bookingsByStationUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/station',
  createCollabUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/admins/collab',
  getCollabsUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/admins/collabs',
  getCollabByIdUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/admins',
  createUsrUrl:'https://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/users'
};
