// export const environment = {
//   lansUrl:'http://localhost:8080/api/lans',
//   newLansUrl:'http://localhost:8080/api/lans/available',
//   boardsUrl:'http://localhost:8080/api/boards',
//   newBoardsUrl:'http://localhost:8080/api/boards/available',
//   newBoardsBookingUrl:'http://localhost:8080/api/bookings/boardbookingclose',
//   openBoardsUrl:'http://localhost:8080/api/bookings/openbookings',
//   lanBookingUrl: 'http://localhost:8080/api/bookings/lanbooking',
//   bookingsByDateUrl: 'http://localhost:8080/api/bookings/bookingsbydate',
//   bookingsById: 'http://localhost:8080/api/bookings/bookingbyid',
//   boardsBySeats: 'http://localhost:8080/api/boards/byseats',
//   loginUrl: 'http://localhost:8080/auth/login',
//   logoutUrl: 'http://localhost:8080/auth/logout',
//   bookingsUrl: 'http://localhost:8080/api/bookings',
//   deleteBookingUrl: 'http://localhost:8080/api/bookings',
//   deleteStationUrl: 'http://localhost:8080/api',
//   updateBoardUrl: 'http://localhost:8080/api/boards',
//   postStationUrl: 'http://localhost:8080/api/save',
//   editBookingUrl:'http://localhost:8080/api/bookings',
//   bookingsByStationUrl:'http://localhost:8080/api/bookings/station',
//   createCollabUrl:'http://localhost:8080/api/admins/collab',
//   getCollabsUrl:'http://localhost:8080/api/admins/collabs',
//   getCollabByIdUrl:'http://localhost:8080/api/admins',
//   createUsrUrl:'http://localhost:8080/api/users'
// };

export const environment = {
  lansUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/lans',
  newLansUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/lans/available',
  boardsUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards',
  newBoardsUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards/available',
  newBoardsBookingUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/boardbookingclose',
  openBoardsUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/openbookings',
  lanBookingUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/lanbooking',
  bookingsByDateUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/bookingsbydate',
  bookingsById: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/bookingbyid',
  boardsBySeats: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards/byseats',
  loginUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/auth/login',
  logoutUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/auth/logout',
  bookingsUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings',
  deleteBookingUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings',
  deleteStationUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api',
  updateBoardUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/boards',
  postStationUrl: 'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/save',
  editBookingUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings',
  bookingsByStationUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/bookings/station',
  createCollabUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/admins/collab',
  getCollabsUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/admins/collabs',
  getCollabByIdUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/admins',
  createUsrUrl:'http://tasty-lavinie-lucagrossi87-8ac74254.koyeb.app/api/users'
};
